-- Tạo bảng DONVI 
CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(50),
    TRGDV VARCHAR2(10)
);

-- Tạo bảng NHANSU
CREATE TABLE NHANSU (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI CHAR(1) CHECK (PHAI IN ('M', 'F')),
    NGSINH DATE,
    PHUCAP NUMBER(10, 2),
    DT VARCHAR2(15),
    VAITRO VARCHAR2(20),
    MADV VARCHAR2(10),
    CONSTRAINT FK_NHANSU_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

-- Thêm khóa ngoại TRGDV sau khi tạo bảng NHANSU
ALTER TABLE DONVI
ADD CONSTRAINT FK_DONVI_TRG FOREIGN KEY (TRGDV) REFERENCES NHANSU(MANV);

-- Tạo bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(50) NOT NULL,
    PHAI CHAR(1) CHECK (PHAI IN ('M', 'F')),
    NGSINH DATE,
    DCHI VARCHAR2(100),
    DT VARCHAR2(15),
    MACT VARCHAR2(10),
    MANGANH VARCHAR2(10),
    SOTCTL NUMBER(3),
    DTBTL NUMBER(4, 2)
);

-- Tạo bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100),
    SOTC NUMBER(2),
    STLT NUMBER(3),
    STTH NUMBER(3),
    SOSVTD NUMBER(3),
    MADV VARCHAR2(10),
    CONSTRAINT FK_HOCPHAN_DONVI FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

-- Tạo bảng KHMO
CREATE TABLE KHMO (
    MAHP VARCHAR2(10),
    HK NUMBER(1) CHECK (HK IN (1, 2, 3)),
    NAM NUMBER(4),
    MACT VARCHAR2(10),
    PRIMARY KEY (MAHP, HK, NAM, MACT),
    CONSTRAINT FK_KHMO_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
);

-- Tạo bảng PHANCONG
CREATE TABLE PHANCONG (
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR2(10),
    PRIMARY KEY (MAGV, MAHP, HK, NAM, MACT),
    CONSTRAINT FK_PHANCONG_NHANSU FOREIGN KEY (MAGV) REFERENCES NHANSU(MANV),
    CONSTRAINT FK_PHANCONG_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
);

-- Tạo bảng DANGKY
CREATE TABLE DANGKY (
    MASV VARCHAR2(10),
    MAGV VARCHAR2(10),
    MAHP VARCHAR2(10),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR2(10),
    DIEMTH NUMBER(4, 2),
    DIEMQT NUMBER(4, 2),
    DIEMCK NUMBER(4, 2),
    DIEMTK NUMBER(4, 2),
    PRIMARY KEY (MASV, MAGV, MAHP, HK, NAM, MACT),
    CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_PHANCONG FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT) REFERENCES PHANCONG(MAGV, MAHP, HK, NAM, MACT)
);
